### ISSUE TITLE
я пудж

### ISSUE THREAD

**Issue by fillander** [Nikolay3308/game1#2]

**Comment by fillander** [comment]
привет я пудж

**Comment by fillander** [comment]
я работаю в доте

**Comment by fillander** [comment]
2

**Comment by fillander** [comment]
там весело

**Comment by fillander** [comment]
гуль приглошаю тебя

**Comment by lokel6957** [comment]
какой у тебя вес

**Comment by fillander** [comment]
a = len(input())
b = len(input())
c = len(input())

if a + b + c == (min(a, b, c) + max(a, b, c))/2*3:
    print("YES")
else:
    print("NO")


вт, 29 нояб. 2022 г. в 19:00, lokel6957 ***@***.***>:

**Comment by fillander** [comment]
import math
x1, x2, y1, y2 = float(input()), float(input()), float(input()),
float(input())
print(math.hypot(x1 - y1, x2 - y2))

чт, 1 дек. 2022 г. в 17:44, артём cthuttdbx ***@***.***>:
