### ISSUE TITLE
кто желает купить у меня детей?

### ISSUE THREAD

**Issue by katyakhvoina0** [Nikolay3308/game1#3]

**Comment by katyakhvoina0** [comment]
50000000 штука

**Comment by fillander** [comment]
я 2 куплю

**Comment by katyakhvoina0** [comment]
окей с тебя 100 000 000

**Comment by katyakhvoina0** [comment]
блин

**Comment by katyakhvoina0** [comment]
с тебя

**Comment by katyakhvoina0** [comment]
да емае

**Comment by katyakhvoina0** [comment]
ты должен

> с тобой

**Comment by katyakhvoina0** [comment]
домооооой

**Comment by ded1emae** [comment]
купите меня мне надоело здесь сидеть

**Comment by katyakhvoina0** [comment]
я выпускаю тебя

**Comment by katyakhvoina0** [comment]
![1](https://user-images.githubusercontent.com/119430048/204580804-9a76088b-8505-4e2b-ba6b-af32ab04312a.jpg)
![2](https://user-images.githubusercontent.com/119430048/204580820-532f2e0d-3049-4ba8-a174-192a7673821c.jpg)

**Comment by katyakhvoina0** [comment]
покушать выбирай
